<?php
$DATA=(array(
	'LOCAL_URL'=>"http://ltw1326.web.cs.unibo.it",
	'SKEPTICAL_NUMBER'=>3,
	'DB_USERNAME'=>"my1332",
	'DB_PASSWORD'>="aenuepoo",
	'DB_NAME'=>"my1332",
	'USER_TABLE'=>"UTENTI",
	'NOTIFY_TABLE'=>"NOTIFICHE",
	'EVENT_TABLE'=>"EVENTI",
	'SUBTYPE_TABLE'=>"SOTTOTIPI"))
?>
